Products/Models/ErrorViewModel.cs
namespace Products.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Products/Models/ProductModel.cs
namespace Products.Models
{
    /// <summary>
    /// A model of a simple product for a demo that only lists products in a mock database
    /// </summary>
    public class ProductModel
    {
        // a string identifier because arithmetic doesn't apply, 001<>1
        public string ProductId { get; set; }

        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }

        // using data URIs for these demo images
        public string Image { get; set; }
    }
}

Products/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Products.Models;

using System.Diagnostics;

namespace Products.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Products/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

using Products.Repositories;
using Products.Services;

namespace Products.Controllers
{
    /// <summary>
    /// Minimal controller that simply displays the list of products when the page is viewed
    /// </summary>
    public class ProductsController : Controller
    {
        // writing to interface unless there's a good reason why not
        private IProductService productService = new ProductService(new ProductRepository());

        public IActionResult Index()
        {
            return View(productService.Products);
        }
    }
}

Products/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Solutionists Products Demo";
}

<div class="text-center">
    <h1 class="display-4">Solutionists Products List Demo</h1>
</div>

Products/Views/Products/Index.cshtml
@model IEnumerable<Products.Models.ProductModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Products List</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <td>
                    <img src="@item.Image" />
                </td>
            </tr>
        }
    </tbody>
</table>

Products/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Products</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Products - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>